### ISSUE TITLE
Not able to start local server

### ISSUE THREAD

**Issue by p16i** [youpin-city/youpin-api#123]
I'm trying to start the service via `docker-compose up` but, I got this error which I'm not sure how to solve it. Do you have any idea?

```
> youpin-api $ docker-compose up api
youpinapi_mongodb_1 is up-to-date
Starting youpinapi_api_1

Attaching to youpinapi_api_1
api_1      |
api_1      | > youpin-api@0.0.0 start /code
api_1      | > node src/
api_1      |

api_1      | module.js:568
api_1      |   return process.dlopen(module, path._makeLong(filename));
api_1      |                  ^
api_1      |
api_1      | Error: Error loading shared library /code/node_modules/grpc/src/node/extension_binary/grpc_node.node: Exec format error
api_1      |     at Error (native)
api_1      |     at Object.Module._extensions..node (module.js:568:18)
api_1      |     at Module.load (module.js:458:32)
api_1      |     at tryModuleLoad (module.js:417:12)
api_1      |     at Function.Module._load (module.js:409:3)
api_1      |     at Module.require (module.js:468:17)
api_1      |     at require (internal/module.js:20:19)
api_1      |     at Object.<anonymous> (/code/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
api_1      |     at Module._compile (module.js:541:32)
api_1      |     at Object.Module._extensions..js (module.js:550:10)
api_1      |     at Module.load (module.js:458:32)
api_1      |     at tryModuleLoad (module.js:417:12)
api_1      |     at Function.Module._load (module.js:409:3)
api_1      |     at Module.require (module.js:468:17)
api_1      |     at require (internal/module.js:20:19)
api_1      |     at Object.<anonymous> (/code/node_modules/grpc/src/node/src/client.js:55:12)
api_1      |     at Module._compile (module.js:541:32)
api_1      |     at Object.Module._extensions..js (module.js:550:10)
api_1      |     at Module.load (module.js:458:32)
api_1      |     at tryModuleLoad (module.js:417:12)
api_1      |     at Function.Module._load (module.js:409:3)
api_1      |     at Module.require (module.js:468:17)
api_1      |
api_1      | npm ERR! Linux 4.4.12-boot2docker
api_1      | npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
api_1      | npm ERR! node v6.3.1
api_1      | npm ERR! npm  v3.10.5
api_1      | npm ERR! code ELIFECYCLE
api_1      | npm ERR! youpin-api@0.0.0 start: `node src/`
api_1      | npm ERR! Exit status 1
api_1      | npm ERR!
api_1      | npm ERR! Failed at the youpin-api@0.0.0 start script 'node src/'.
api_1      | npm ERR! Make sure you have the latest version of node.js and npm installed.
api_1      | npm ERR! If you do, this is most likely a problem with the youpin-api package,
api_1      | npm ERR! not with npm itself.
api_1      | npm ERR! Tell the author that this fails on your system:
api_1      | npm ERR!     node src/
api_1      | npm ERR! You can get information on how to open an issue for this project with:
api_1      | npm ERR!     npm bugs youpin-api
api_1      | npm ERR! Or if that isn't available, you can get their info via:
api_1      | npm ERR!     npm owner ls youpin-api
api_1      | npm ERR! There is likely additional logging output above.
api_1      |
api_1      | npm ERR! Please include the following file with any support request:
api_1      | npm ERR!     /code/npm-debug.log
youpinapi_api_1 exited with code 1
```

**Comment by supasate** [comment]
Which platform are you working on?

**Comment by p16i** [comment]
OSX

**Comment by supasate** [comment]
Let me check.

**Comment by supasate** [comment]
Seems strange. Actually, this error ever happened before. I fixed by [adding libc6-compat to the alpine base image](https://github.com/youpin-city/youpin-api/blob/402c3375adcddb0040e22de5ab29bc2cfc9f4456/Dockerfile#L5).

I can reproduce this problem by removing that line and rebuild the image. But if that line is there, I can run the container without any error.

Could you try to remove that docker image and rebuild it again?

**Comment by p16i** [comment]
nope, it doesn't help :/

**Comment by supasate** [comment]
Which Docker engine do you use? Docker for Mac OS or Docker Toolbox?

**Comment by p16i** [comment]
I’m using Docker Toolbox.

**Comment by supasate** [comment]
I use Docker for Mac OS. Could you try it?

**Comment by p16i** [comment]
I have tried already and the problem still occurs.

**Comment by p16i** [comment]
fixed by removing `node_modules` directory.
